# fly.toml app configuration file generated for project-3-backend on 2024-02-09T11:48:25+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'project-3-backend'
primary_region = 'sin'

[build]
 
 [deploy]
  release_command = "sh ./release.sh"
 
 [env]
  PORT = "3000"
  USERNAME = "postgres"
  PASSWORD = "p3iQ46EYGK0sjzs"
  DATABASE = "project_3_database"
  HOST = "project-3-backend-db.internal"
  DIALECT = "postgres"
  NODE_ENV = "production"
  AUTH_AUDIENCE = "https://RA-project3/api" 
  AUTH_ISSUER = "https://dev-yazofxh8rwdpn6nq.us.auth0.com/"
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
